### ISSUE TITLE
Federation tester fails to parse well-known if response spans multiple tcp segments

### ISSUE THREAD

**Issue by meramsey** [matrix-org/matrix-federation-tester#153]
I know there was another issue https://github.com/matrix-org/fed-tester-ui/issues/36 was closed which is similiar.  

This should still be address because the federation tester is just trying IP:8448 no matter what the well known delegation says  which it should be trying vs just resolving the domain to IP and trying IP:8448
https://element-hq.github.io/synapse/latest/delegate.html#delegation-of-incoming-federation-traffic

Federation test seems to always resolve to the IP:8448 even with 
/.well-known/matrix/client
```
{
  "io.element.e2ee": {
    "secure_backup_required": false,
    "secure_backup_setup_methods": ["passphrase"]
  },
  "m.homeserver": {
      "base_url": "https://matrix.mydomain.com"
  }
}
```

/.well-known/matrix/server
```
{
    "m.server": "matrix.mydomain.com:443"
}
```

homeserver.yaml
```
server_name: "matrix.mydomain.com"
public_baseurl: "https://matrix.mydomain.com/"
report_stats: false
pid_file: "/var/run/matrix-synapse.pid"
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['::1', '127.0.0.1']
    resources:
      - names: [client, federation]
        compress: false
database:
  name: psycopg2
  args:
    user: dbadmin
    password: redacted
    database: synapse
    host: 127.0.0.1
    cp_min: 5
    cp_max: 10
log_config: "/etc/matrix-synapse/log.yaml"
media_store_path: /var/lib/matrix-synapse/media
signing_key_path: "/etc/matrix-synapse/homeserver.signing.key"
enable_registration: true
registration_requires_token: true
registration_shared_secret: "redacted"
trusted_key_servers:
  - server_name: ""
turn_uris: [ ]
turn_allow_guests: false
next_link_domain_whitelist: []
#federation_domain_whitelist: []
serve_server_wellknown: true
default_identity_server: ""
enable_federation: true
allow_public_rooms_over_federation: true
allow_profile_lookup_over_federation: true
enable_3pid_lookup: false
allow_guest_access: false
encryption_enabled_by_default_for_room_type: all
password_config:
  pepper: "redacted"
max_upload_size: 1500M
user-directory:
  enabled: true
  prefer_local_users: true
  search_all_users: true
auto_join_rooms:
  - "#community:matrix.mydomain.com"
autocreate_auto_join_rooms: true
autocreate_auto_join_rooms_federated: false
ip_range_whitelist:
  - '127.0.0.1'
  - '0.0.0.0/0'
app_service_config_files:
   - '/etc/matrix-synapse/mautrix-signal-registration.yaml'
```

I did on a dynamic domain and took screenshots for reference
It complained and never followed the delegation which is properly configured and it should have been following
![Screenshot from 2024-10-29 11-35-10](https://github.com/user-attachments/assets/b6714124-3f95-4fc4-b968-0d89a330046f)
![Screenshot from 2024-10-29 11-22-46](https://github.com/user-attachments/assets/f2c5b8f6-4456-4e5d-9ac6-8fda84668e44)

Can see /.well-known/matrix/client and /.well-known/matrix/server were properly working and responding and also if it had followed delegation it would have been able to resolve the other urls properly too.
![Screenshot from 2024-10-29 11-22-16](https://github.com/user-attachments/assets/a405116f-3346-4568-8acd-32204f53fa8b)
![Screenshot from 2024-10-29 11-22-25](https://github.com/user-attachments/assets/bdd9965e-c8bf-4074-82bb-4f73874d3457)
![Screenshot from 2024-10-29 11-23-09](https://github.com/user-attachments/assets/c2ccce46-d8ee-448f-b4fe-11324211186b)
![Screenshot from 2024-10-29 11-23-49](https://github.com/user-attachments/assets/6478bf67-e4d2-4748-9b58-1a68698e90d3)
